---
#output: github_document
always_allow_html: true
output:
  rmdformats::robobook:
    self_contained: true
    lightbox: true
    gallery: false
    highlight: tango
---

# About Me

I am a student at Mathematical Science Department, [Universiti Brunei Darussalam](https://ubd.edu.bn/). I live (permanently) in Mataram, West Nusa Tenggara, Indonesia and being (temporarily) in Brunei. 
Currently I work on my recent research project related to spatial modelling for Gaussian data with Bayesian hierarchical model as well as conditional auto-regressive (CAR) model to explain the spatial structure in the neighborhood area. I also learn R to support my project.

***

# Interest

Spatial modelling, Bayesian statistics, Conditional Auto-regressive model, Multilevel spatial data model

***

# Education

* MSc in Mathematics, 2012, [Institut Teknologi Bandung (ITB)](https://www.itb.ac.id/), Bandung, Indonesia

* BSc in Mathematics, 2009, [Institut Teknologi Sepuluh Nopember (ITS)](https://www.its.ac.id/), Surabaya Indonesia

***

# Skills

R Programming, Python, Statistical data analysis
